name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pytest

      - name: Lint with black
        run: |
          black --check --diff app test src

      - name: Build Docker image
        run: docker build -t credit-predict-api -f Dockerfile .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name credit-api credit-predict-api

      - name: Wait for container to be ready
        run: sleep 5

      - name: Run all tests
        run: pytest
